spring:
  data:
    mongodb:
      uri: mongodb+srv://test:test@cluster0.kpcudmd.mongodb.net/cash
ledger:
  base-url: http://localhost:8081
logging:
  level:
    org.springframework.web.reactive.function.client.exchangeFunctions: TRACE
server:
  port: 8081
